spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:4455/testdb0319?createdatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create